-- Simple apps table as requested
CREATE TABLE IF NOT EXISTS public.apps (
  id bigint generated by default as identity not null,
  name text null,
  status boolean null,
  constraint apps_pkey primary key (id)
) TABLESPACE pg_default;

-- Insert test data with id = 1
INSERT INTO public.apps (id, name, status) 
VALUES (1, 'Homework App', true)
ON CONFLICT (id) DO NOTHING;